image: alpine

stages:
    - build
    - deploy

build:
    stage: build
    before_script:
        - apk update && apk add doxygen
    script:
        doxygen
    artifacts:
        paths:
            - documentation/

deploy:
    stage: deploy
    when: on_success
    needs: [build]
    dependencies:
        - build
    before_script:
        - mkdir -p ~/.ssh
        - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - apk update && apk add openssh-client
    script:
        - ssh deployuser@elon.sdsurocketproject.org "rm -rf /var/www/html/wikistatic/far-mars-onboard-firmware/*"
        - scp documentation/html/* deployuser@elon.sdsurocketproject.org:/var/www/html/wikistatic/far-mars-onboard-firmware
    only:
        - master
