var annotated_dup =
[
    [ "batteryData", "structbattery_data.html", "structbattery_data" ],
    [ "batteryFloatData", "structbattery_float_data.html", "structbattery_float_data" ],
    [ "bno055_accel_float_t", "structbno055__accel__float__t.html", "structbno055__accel__float__t" ],
    [ "bno055_accel_offset_t", "structbno055__accel__offset__t.html", "structbno055__accel__offset__t" ],
    [ "bno055_accel_t", "structbno055__accel__t.html", "structbno055__accel__t" ],
    [ "bno055_euler_float_t", "structbno055__euler__float__t.html", "structbno055__euler__float__t" ],
    [ "bno055_euler_t", "structbno055__euler__t.html", "structbno055__euler__t" ],
    [ "bno055_gravity_float_t", "structbno055__gravity__float__t.html", "structbno055__gravity__float__t" ],
    [ "bno055_gravity_t", "structbno055__gravity__t.html", "structbno055__gravity__t" ],
    [ "bno055_gyro_float_t", "structbno055__gyro__float__t.html", "structbno055__gyro__float__t" ],
    [ "bno055_gyro_offset_t", "structbno055__gyro__offset__t.html", "structbno055__gyro__offset__t" ],
    [ "bno055_gyro_t", "structbno055__gyro__t.html", "structbno055__gyro__t" ],
    [ "bno055_linear_accel_float_t", "structbno055__linear__accel__float__t.html", "structbno055__linear__accel__float__t" ],
    [ "bno055_linear_accel_t", "structbno055__linear__accel__t.html", "structbno055__linear__accel__t" ],
    [ "bno055_mag_float_t", "structbno055__mag__float__t.html", "structbno055__mag__float__t" ],
    [ "bno055_mag_offset_t", "structbno055__mag__offset__t.html", "structbno055__mag__offset__t" ],
    [ "bno055_mag_t", "structbno055__mag__t.html", "structbno055__mag__t" ],
    [ "bno055_quaternion_t", "structbno055__quaternion__t.html", "structbno055__quaternion__t" ],
    [ "bno055_sic_matrix_t", "structbno055__sic__matrix__t.html", "structbno055__sic__matrix__t" ],
    [ "bno055_t", "structbno055__t.html", "structbno055__t" ],
    [ "cpuTemperatureData", "structcpu_temperature_data.html", "structcpu_temperature_data" ],
    [ "cpuTemperatureFloatData", "structcpu_temperature_float_data.html", "structcpu_temperature_float_data" ],
    [ "daqSensors", "structdaq_sensors.html", "structdaq_sensors" ],
    [ "hallEffectData", "structhall_effect_data.html", "structhall_effect_data" ],
    [ "pressureConvertedDataADC0", "structpressure_converted_data_a_d_c0.html", "structpressure_converted_data_a_d_c0" ],
    [ "pressureConvertedDataADC1", "structpressure_converted_data_a_d_c1.html", "structpressure_converted_data_a_d_c1" ],
    [ "pressureDataADC0", "structpressure_data_a_d_c0.html", "structpressure_data_a_d_c0" ],
    [ "pressureDataADC1", "structpressure_data_a_d_c1.html", "structpressure_data_a_d_c1" ],
    [ "sensorMessage", "structsensor_message.html", "structsensor_message" ],
    [ "strData", "structstr_data.html", "structstr_data" ],
    [ "thermocoupleData", "structthermocouple_data.html", "structthermocouple_data" ]
];