var searchData=
[
  ['sam_20analog_2dto_2ddigital_20converter_20_28adc_29_20driver',['SAM Analog-to-Digital Converter (ADC) Driver',['../group__asfdoc__sam0__adc__group.html',1,'']]],
  ['sam_20port_20_28port_29_20driver',['SAM Port (PORT) Driver',['../group__asfdoc__sam0__port__group.html',1,'']]],
  ['sam_20rtc_20calendar_20_28rtc_20cal_29_20driver',['SAM RTC Calendar (RTC CAL) Driver',['../group__asfdoc__sam0__rtc__calendar__group.html',1,'']]],
  ['sam_20sigma_2ddelta_20analog_2dto_2ddigital_20converter_20_28sdadc_29_20driver',['SAM Sigma-Delta Analog-to-Digital Converter (SDADC) Driver',['../group__asfdoc__sam0__sdadc__group.html',1,'']]],
  ['sam_20serial_20peripheral_20interface_20_28sercom_20spi_29_20driver',['SAM Serial Peripheral Interface (SERCOM SPI) Driver',['../group__asfdoc__sam0__sercom__spi__group.html',1,'']]],
  ['sam_20serial_20usart_20_28sercom_20usart_29_20driver',['SAM Serial USART (SERCOM USART) Driver',['../group__asfdoc__sam0__sercom__usart__group.html',1,'']]],
  ['sam_20system_20clock_20management_20_28system_20clock_29_20driver',['SAM System Clock Management (SYSTEM CLOCK) Driver',['../group__asfdoc__sam0__system__clock__group.html',1,'']]],
  ['sam_20system_20_28system_29_20driver',['SAM System (SYSTEM) Driver',['../group__asfdoc__sam0__system__group.html',1,'']]],
  ['sam_20system_20interrupt_20_28system_20interrupt_29_20driver',['SAM System Interrupt (SYSTEM INTERRUPT) Driver',['../group__asfdoc__sam0__system__interrupt__group.html',1,'']]],
  ['sam_20system_20pin_20multiplexer_20_28system_20pinmux_29_20driver',['SAM System Pin Multiplexer (SYSTEM PINMUX) Driver',['../group__asfdoc__sam0__system__pinmux__group.html',1,'']]],
  ['status_20and_20control_20registers',['Status and Control Registers',['../group___c_m_s_i_s___c_o_r_e.html',1,'']]],
  ['systick_20functions',['SysTick Functions',['../group___c_m_s_i_s___core___sys_tick_functions.html',1,'']]],
  ['system_20control_20block_20_28scb_29',['System Control Block (SCB)',['../group___c_m_s_i_s___s_c_b.html',1,'']]],
  ['system_20tick_20timer_20_28systick_29',['System Tick Timer (SysTick)',['../group___c_m_s_i_s___sys_tick.html',1,'']]],
  ['status',['Status',['../group___e__status_group.html',1,'']]],
  ['status_20codes',['Status Codes',['../group__group__sam0__utils__status__codes.html',1,'']]],
  ['statistics_20functions',['Statistics Functions',['../group__group_stats.html',1,'']]],
  ['support_20functions',['Support Functions',['../group__group_support.html',1,'']]],
  ['sam_20parts',['SAM parts',['../group__sam__part__macros__group.html',1,'']]],
  ['samc21_20device_20definitions',['SAMC21 Device Definitions',['../group___s_a_m_c21__definitions.html',1,'']]],
  ['sigma_2ddelta_20analog_20digital_20converter',['Sigma-Delta Analog Digital Converter',['../group___s_a_m_c21___s_d_a_d_c.html',1,'']]],
  ['serial_20communication_20interface',['Serial Communication Interface',['../group___s_a_m_c21___s_e_r_c_o_m.html',1,'']]],
  ['supply_20controller',['Supply Controller',['../group___s_a_m_c21___s_u_p_c.html',1,'']]],
  ['samc21e15a_20definitions',['SAMC21E15A definitions',['../group___s_a_m_c21_e15_a__definitions.html',1,'']]],
  ['samc21e16a_20definitions',['SAMC21E16A definitions',['../group___s_a_m_c21_e16_a__definitions.html',1,'']]],
  ['samc21e17a_20definitions',['SAMC21E17A definitions',['../group___s_a_m_c21_e17_a__definitions.html',1,'']]],
  ['samc21e18a_20definitions',['SAMC21E18A definitions',['../group___s_a_m_c21_e18_a__definitions.html',1,'']]],
  ['samc21g15a_20definitions',['SAMC21G15A definitions',['../group___s_a_m_c21_g15_a__definitions.html',1,'']]],
  ['samc21g16a_20definitions',['SAMC21G16A definitions',['../group___s_a_m_c21_g16_a__definitions.html',1,'']]],
  ['samc21g17a_20definitions',['SAMC21G17A definitions',['../group___s_a_m_c21_g17_a__definitions.html',1,'']]],
  ['samc21g18a_20definitions',['SAMC21G18A definitions',['../group___s_a_m_c21_g18_a__definitions.html',1,'']]],
  ['samc21j15a_20definitions',['SAMC21J15A definitions',['../group___s_a_m_c21_j15_a__definitions.html',1,'']]],
  ['samc21j16a_20definitions',['SAMC21J16A definitions',['../group___s_a_m_c21_j16_a__definitions.html',1,'']]],
  ['samc21j17a_20definitions',['SAMC21J17A definitions',['../group___s_a_m_c21_j17_a__definitions.html',1,'']]],
  ['samc21j18a_20definitions',['SAMC21J18A definitions',['../group___s_a_m_c21_j18_a__definitions.html',1,'']]],
  ['sd_2fmmc_20protocol_20definition',['SD/MMC Protocol Definition',['../group__sd__mmc__protocol.html',1,'']]],
  ['sd_2fmmc_2fsdio_20common_20stack',['SD/MMC/SDIO common stack',['../group__sd__mmc__stack__group.html',1,'']]],
  ['sd_2fmmc_20memory',['SD/MMC Memory',['../group__sd__mmc__stack__mem.html',1,'']]],
  ['serial_20interface_20_28serial_29',['Serial Interface (Serial)',['../group__serial__group.html',1,'']]],
  ['square_20root',['Square Root',['../group___s_q_r_t.html',1,'']]]
];
